application: michael-brown
version: 8
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/glider.ico
  upload: static/glider.ico
- url: /blog.*
  script: Blog.app
- url: /static
  static_dir: static
- url: /.*
  script :  home.app

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest   
